Repository allwagelab/client, pull requests merged in 2025-01, with the labels that each got.

#17 chore: D-n 규칙에 따라 자동으로 Label 을 업데이트하는 Github Actions
  .github/workflow/d-day-labeler.yml
Labels: enhancement, D-3

#20 fix: AuthProvider의 refreshTokenHandler 관련 버그 수정
  .github/workflows/d-day-labeler.yml
  packages/message-bus/src/with-auth/AuthProvider.tsx
Labels: bug, D-3

#18 토큰 만료 시 자동 갱신 기능 관련
  .github/workflows/d-day-labeler.yml
  packages/message-bus/src/with-auth/AuthProvider.tsx
  web/src/apis/auth.ts
  web/src/apis/index.ts
  web/src/hooks/useAxiosPrivate.ts
  web/src/hooks/useRefreshToken.ts
Labels: D-3

#21 로그인 및 회원가입 시 사용되는 메시지 상수화
  packages/constants/src/MESSAGES.ts
  packages/constants/src/index.ts
  packages/message-bus/package.json
  packages/message-bus/src/with-auth/AuthProvider.tsx
  pnpm-lock.yaml
  web/src/apis/auth.ts
  web/src/components/auth/SignupModal/AccountForm.tsx
  web/src/components/auth/SignupModal/BusinessForm.tsx
  web/src/hooks/useRefreshToken.ts
  web/src/pages/auth/FindId.tsx
  web/src/pages/auth/FindPassword.tsx
  web/src/pages/auth/Login.tsx
Labels: D-3

#24 헤더, 네비게이션 디자인
  web/public/icons/alarm.svg
  web/public/icons/building.svg
  web/public/icons/calendar.svg
  web/public/icons/card.svg
  web/public/icons/employee.svg
  web/public/icons/headphone.svg
  web/public/icons/home.svg
  web/public/icons/receipt.svg
  web/public/icons/setting.svg
  web/public/icons/user.svg
  web/src/components/layout/Private.tsx
  web/src/components/ui/Header/Header.tsx
  web/src/components/ui/Navigation/Navigation.tsx
Labels: D-3

#25 fix: d-day-labeler action
  .github/workflows/d-day-labeler.yml
Labels: bug
